### ISSUE TITLE
Error moment/moment"' has no default export

### ISSUE THREAD

**Issue by naveedahmed1** [IckleChris/ic-datepicker#1]
The plugin looks awesome, but I am receiving below error when I try to use this plugin:

`node_modules/moment/moment"' has no default export.`

On all files having below import:

`import Moment from 'moment';`

Can you please guide?

I would really appreciate if you could please also share the settings required for systemjs.config?

**Comment by IckleChris** [comment]
This issue plagued me throughout development of the component, although both the demo that uses the datepicker and an angular-cli project I have both don't face this error so I thought it was resolved. I'll have to look into it some more.

As for systemjs I will have to set up a test project using the loader and try it out - still on the todo list.

**Comment by naveedahmed1** [comment]
Thank you so much Chris, looking forward to use it in my project :)

**Comment by IckleChris** [comment]
Are you able to provide an example plunkr/similar that reproduces the issue?

**Comment by naveedahmed1** [comment]
@IckleChris its a private project otherwise I would have share the repo. But I believe it should throw same error for any project built without angular-cli, as you mentioned above.

**Comment by IckleChris** [comment]
@naveedahmed1 The demo within the repo (the documentation app) is an angular cli project and I don't get the issue there. I also don't get the issue in my private angular cli project.

**Comment by naveedahmed1** [comment]
@IckleChris I just came across this stackoverflow question http://stackoverflow.com/questions/36893165/importing-moment-into-typescript-project

and it seems that we should have:

`import * as Moment from 'moment';`

instead of

`import Moment from 'moment';`

Can you please have a look?

**Comment by IckleChris** [comment]
@naveedahmed1 I've tried the latter syntax and it causes various build errors, the syntax current in the project is the only syntax that compiles. I'm going to have to look into this more this weekend.

For reference I believe it was [this resource](https://forum.ionicframework.com/t/error-from-rollup-when-importing-moment-js-with-rc0/64902/2) that led to the syntax used as this library uses rollup.

Is your project an Angular CLI project?

**Comment by IckleChris** [comment]
@naveedahmed1 release `0.0.5` has replaced Rollup with Webpack for bundling, and the source code now works with `import * as Moment from 'moment'` syntax. I've testing in all of my projects and they still work fine, so can you please test and report?

**Comment by naveedahmed1** [comment]
Thanks @IckleChris the issue has been fixed.

Few more thing, since these are minor I am adding here:

In usage section https://github.com/IckleChris/ic-datepicker#usage please update the selector in example it should be **ic-datepicker** and not **ic-datepicker-component**

`<ic-datepicker formControlName="datepicker" options="datepickerOptions"></ic-datepicker>`


The docs and examples page https://icklechris.github.io/ic-datepicker/ doesn't seem to work.

In options please add support to customize colors.

In my case the datepicker appears 48 pixels below the input due to this class:

```
.ic-datepicker.bottom {
    top: 48px;
}
```

in my opinion top should be 0px;

I think we should also add below instructions for systemjs configuration
in maps add:
`'ic-datepicker/dist': 'node_modules/ic-datepicker/dist/bundles',`

in packages add:

`'ic-datepicker/dist': { defaultExtension: "js", main: "ic-datepicker.bundle.js" }`

**Comment by IckleChris** [comment]
Thanks, Demo page is fixed.

Regarding the styles point, I intentionally turned off `ViewEncapsulation` on the component so you can just override styles using CSS. I'll probably update it to 0 but we'll see. 

As for Systemjs I need to set up a systemjs project and try it out before I add instructions - if you have an example or experience then feel free to submit a PR to update accordingly.

**Comment by naveedahmed1** [comment]
Thank you @IckleChris does it support material icons? Since with Angular 2 apps most people use Google Material Icons, if its support could be added it would be great :)

Can you please also check if minDate and maxDate are working properly?

I set below options

```
this.datepickerOptions = {
            minDate: Moment().add(3, 'day'),
            maxDate: Moment().add(3, 'month')
        };
```

And assigned the default value of  **04/06/2017** to the formcontrol.

When I click the form control it shows the default value **Apr 04, 2017** as selected date on date picker, whereas the Previous Month control is disabled. When I click Next month and then click Previous Month, it enables Previous Month control for the month of April as well which is shown as disabled in start.

**Comment by IckleChris** [comment]
> most people use Google Material icons

I don't think that's necessarily true but of course I want to support their usage. I'll have a look at that and the dates.

**Comment by naveedahmed1** [comment]
One suggestion, when the minDate and maxDate is specified the Years that doean't fall in the specified date range should be disabled.

Can you please share the styles (classes or selectors) that needs to be overridden to customize look.

Please also confirm if you got a chance to take a look at https://github.com/IckleChris/ic-datepicker/issues/1#issuecomment-284266499

**Comment by IckleChris** [comment]
For overriding styles look at: http://stackoverflow.com/questions/36527605/how-to-style-child-components-from-parent-components-css-file - The method varies slightly depending on if you're using `angular-cli` or not, but it's relatively straightforward.

The `0.0.6` release fixes the min/max date year selection issue and also adds support for Material Icons. Note the configuration required for icons has changed slightly and will need updating if you have an existing implementation. You can see the Material icons example on the [demo page](https://icklechris.github.io/ic-datepicker/options/icons).

**Comment by naveedahmed1** [comment]
That's awesome! Thank you so much for the update.

Sadly, the min/max date year selection issue still exists with 0.0.6 release. Can you please have a look?

**Comment by IckleChris** [comment]
What do you think the behaviour should be in this situation;

Minimum date is 1st February 2017
Maximum date 21st March 2017
Default (selected) date in the datepicker is 1st June 2017

Should the datepicker;

1. When clicked, open displaying the month of June, with the **>** button hidden and the **<** button displayed, so the user can manually click back to the available months.
2. Still display **01/06/2017** in the input field but when opening the datepicker display the closest allowed month to the selected date (so in this case March)
3. Something else?

I've fixed the issue with the wrong arrows displaying, and currently it behaves as point 1 above, but I guess now is the time to resolve this. I'm fairly convinced point 2 is the better UX here.

**Comment by naveedahmed1** [comment]
In both of the cases if the user submits the form without interacting with datepicker, would it post the selected date to the server i.e. 01/06/2017? if so, then it would be skipping the min/max date range validator.

What if we set the selected value to null if it doesn't fall between the min/max date range?

Regarding point 2, if the selected value is 01/06/2017 and user submit form without selecting a valid date the server might return error of invalid date(which it should if min/max validation is in place), it will result in a server round trip and probably wont be a pleasant user experience. Though this could be avoided, if the date validity is checked before posting data but for this additional validator would need to be applied for min/max date.

**Comment by IckleChris** [comment]
Yeah I considered that initially but this is only on initial load of the component - that therefore means that although that date falls outside of the boundaries of the min/max dates something coded by the developer allowed that date to be selected in the first place.

I can imagine there being cases where an initial date may be outside of those boundaries but a user can only select a different date within the min/max. For example a form that only allows you to select a date in the future, but you can revisit after that date and update it (for some reason) would probably require that initial date to still be displayed.

Anyway, it seems like something that should maybe be configurable, but default to nullifying and displaying a console warning (which it actually already does) if the date is invalid.

**Comment by naveedahmed1** [comment]
Agree with what you proposed, making it configurable would be great! 

I was wondering if the selected date doesn't fall between the min/max date range will it make the formcontrol status invalid without any need to an additional validator?

**Comment by IckleChris** [comment]
Hmm good question! I'll have to check on validity when I get back on this in the morning

**Comment by IckleChris** [comment]
So, version `0.0.8` will, by default, nullify the model value if the datepicker is instantiated with a date that is invalid due to min/max date values provided. The datepicker itself won't allow you to select a date outside of that range (the options are disabled and there is additional validation within to prevent that) so instantiation is the only time that could occur. I think marking the field as being invalid is as simple as adding the `required` validator to the field. If its value is cleared, or it is instantiated with an invalid date the field will be marked as invalid.

**Comment by naveedahmed1** [comment]
Sounds great, I wont suggest adding required to datepicker itself, since there could be situations where the field could be optional yet if a value is selected it must be between min/max.

To properly display validation errors, I believe developer will have to add validators to formgroup.

**Comment by IckleChris** [comment]
Yeah that's what I meant - the user would add the `required` validator to their form configuration 👍

**Comment by IckleChris** [comment]
@naveedahmed1 Would you mind checking the state of this issue from your perspective and close / create new issues as appropriate? This issue has spiralled into a bit of a monster.

**Comment by naveedahmed1** [comment]
haha I was thinking the same :)

Since the release 0.0.5 (https://github.com/IckleChris/ic-datepicker/issues/1#issuecomment-284177799) fixed the original issue of no default export, I am closing this issue.
