### ISSUE TITLE
Placeholder text

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [IckleChris/ic-datepicker#11]
Is it possible to add placeholder text to the datepicker input element?

**Comment by IckleChris** [comment]
It is - I've just added a docs page for the `attrs` option [here](https://icklechris.github.io/ic-datepicker/options/attrs). Apologies, not sure why this wasn't documented! Basically you can use the following;

```typescript
options: IcDatepickerOptions = {
  attrs: {
    placeholder: 'My Placeholder Value'
  }
};
```

```html
<ic-datepicker [options]="options"></ic-datepicker>
```

Hope that helps!

**Comment by tobi-or-not-tobi** [comment]
Awesome! Thx or the prompt reply, much appreciated!
