### ISSUE TITLE
Is it possible to localize labels? 

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [IckleChris/ic-datepicker#12]
I'd like to have the ability to localize the month and day labels as well as the today / tomorrow actions. Can this be done by providing a configuration?

**Comment by IckleChris** [comment]
You can change the date related labels (month names, day names etc) by updating the locale used by MomentJS (http://momentjs.com/docs/#/i18n/). As for the today/tomorrow options they are just default values provided for the [`dayQuickOptions`](https://icklechris.github.io/ic-datepicker/options/dayQuickOptions) config option - you can override those and change the labels by providing them yourself. Hopefully this helps!

**Comment by tobi-or-not-tobi** [comment]
Thanks for the response. The dayQuickOptions are cool, works fine (using `import * as moment from 'moment';`). I was hoping to fallback on standard support from momentjs, since they seem to support all kind of languages including dutch. I've provided the locale in my module providers:

```
    providers: [
        {
            provide: LOCALE_ID, useValue: 'nl-NL'
        }
    ]
```

But its not been picked up moment. I understand this is not related to your module, but in case you know, I appreciate your help.

**Comment by IckleChris** [comment]
I'm yet to come across an example where the locale is overridden by a provider, where did you come across that? All examples I've seen call the `moment.locale()` function directly (as in [https://github.com/urish/angular2-moment/issues/26](https://github.com/urish/angular2-moment/issues/26)

**Comment by tobi-or-not-tobi** [comment]
I haven't used it together with moment, I used it for the DatePipe, see https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html. I'll see if I can get an answer with the momentjs team.
