### ISSUE TITLE
Instructions for systemjs.config.js?

### ISSUE THREAD

**Issue by NullableMe** [IckleChris/ic-datepicker#13]
Hi, 
I followed the instructions on the installation-page, but when I try to start the app it can’t find the ic-datepicker and throws a 404 and a ZoneAwareError. I’m guessing I need to add some reference in systemjs.config but I do not know how. I found a comment by @naveedahmed1 about this in another issue-thread here, but it did not work for me. 

> I think we should also add below instructions for systemjs configuration
in maps add:
'ic-datepicker/dist': 'node_modules/ic-datepicker/dist/bundles',
in packages add:
'ic-datepicker/dist': { defaultExtension: "js", main: "ic-datepicker.bundle.js" 
> }

This is probably a trivial problem but I’m pretty new to Angular and still learning. Just for reference, I’m using Angular 4 and ic-datepicker is set to 0.0.10 in the package.json.
Thanks in advanced.

**Comment by IckleChris** [comment]
Hey - I have 0 experience with SystemJS sadly so I'm only guessing, but from looking at the code snippet you pulled across above try replacing `ic-datepicker/dist` with `ic-datepicker`. In initial versions imports were `import { IcDatepickerModule } from 'ic-datepicker/dist'` but the `/dist` has been dropped since.

**Comment by NullableMe** [comment]
Thanks for the quick reply. I have already tried the brute force approach of trying different paths and names. I also tried your suggestion again but with no luck. I guess I have to drop the systemjs-approach and go with Angular CLI?

**Comment by IckleChris** [comment]
If you're new to Angular I'd recommend using Angular CLI regardless (that's just my personal recommendation) and from what I understand the usage of SystemJS in Angular is dropping in favour of Webpack/Rollup. I still think it should be documented how to use this component in a SystemJS setup however I need to be able to set up a SystemJS Angular project to figure it out.

**Comment by NullableMe** [comment]
I have successfully managed to migrate my project to Angular CLI. And it works brilliant. Thanks for the help.

One last question, is it possible to use the ic-datepicker with material input?

**Comment by IckleChris** [comment]
No problem! 

Not currently, but I will look into implementing that hopefully this weekend and update you.

**Comment by IckleChris** [comment]
Apologies for the (long!) delay with this. As an update I have recently been working on this component to move its content to a different project foundation, and in doing so have implemented the ability to provide a custom input template (which works for Angular Material as an example). This should be pushed and released in the coming days.

**Comment by IckleChris** [comment]
Release `0.1.0` adds support for providing custom input templates [as documented here](https://icklechris.github.io/ic-datepicker/input-template). An example (including an Angular Material input) can be found [here](https://icklechris.github.io/ic-datepicker/example).
