### ISSUE TITLE
Hide last empty row for months that don't need it

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [IckleChris/ic-datepicker#14]
A number of months do not need the last row. Would be nice if this row is hidden for those months that can live without. I can imagine some designs would prefer to have a static layout (i.e. not shrinking during every month toggle), so in case you like to honor this request, I'd make it configurable. 

![image](https://cloud.githubusercontent.com/assets/4745807/24818351/712a116e-1be0-11e7-8d24-6bbca7d7b870.png)

**Comment by IckleChris** [comment]
This has been implemented in `v0.0.11` - `showEmptyRow` is the config option ([link to docs page](https://icklechris.github.io/ic-datepicker/options/showEmptyRow)). Let me know if you have any issues!
