### ISSUE TITLE
Input readonly not working

### ISSUE THREAD

**Issue by edmilsonlani** [IckleChris/ic-datepicker#15]
The field does not respect the property readonly.

`this.datepickerOptions = {
            showEmptyRow: false,
            showDayQuickOptions: false,
            inputClasses: ['form-control', 'group-left'],
            attrs: {
                placeholder: 'de',
                readonly: false
            }
        };`

`<ic-datepicker [options]="datepickerOptions"></ic-datepicker>`

The result in browser:

`<input type="text" class="form-control group-left" ng-reflect-ng-class="form-control,group-left" placeholder="de" readonly="true">`

**Comment by IckleChris** [comment]
Apologies for the delay, this should be fixed in `0.0.12`. Let me know if there are any other issues.
