### ISSUE TITLE
Input-Group & ngModel

### ISSUE THREAD

**Issue by leomayer** [IckleChris/ic-datepicker#17]
Is there a complete sample to group the ic-datepicker in an 'input-group'? I'm looking for a input-field and then two buttons (clear & toogle calendar) which could be grouped nicely with the 'input-group' and 'input-group-addon'. But I failed miserably with the approach since the input-field was still aligned  on the far left side and the popup did not display the way as expected (either nothing, red square, 3 line popup with very long row of dates).

And the second request is for a sample how to use [(ngModel)] properly with the component.

**Comment by IckleChris** [comment]
Sorry for the delay - I have recently been working on stablising this component (mainly moving it to a different build process/foundation) and in doing so have implemented the ability to provide custom input templates to the component, which should allow you to achieve what you mention above. I'm aiming for this to be released in the next few days once I'm happy with testing.

**Comment by IckleChris** [comment]
Release `0.1.0` includes the ability to [provide custom templates](https://icklechris.github.io/ic-datepicker/input-template) to facilitate input groups.

Also included in the [installation documenatation](https://icklechris.github.io/ic-datepicker/installation) is an example of using `ngModel`.
