### ISSUE TITLE
import to ionic 3 got error

### ISSUE THREAD

**Issue by kiko555** [IckleChris/ic-datepicker#19]
Error: StaticInjectorError[IcDatepickerService]: 
StaticInjectorError[IcDatepickerService]: 
NullInjectorError: No provider for IcDatepickerService!

I had follow the readme, but still got error.

**Comment by svoychik** [comment]
I got the same error. Adding IcDatepickerModule.forRoot() to root module solves the issue

**Comment by IckleChris** [comment]
Thanks @svoychik that is correct, the README/docs are incorrect and require updating.
