### ISSUE TITLE
Production builds with AoT Fails

### ISSUE THREAD

**Issue by naveedahmed1** [IckleChris/ic-datepicker#3]
In case of Angular Clli the productions build with AoT (ng build --prod --aot) are failing with below error, can you please have a look:

`
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in node_modules/ic-datepicker/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in node_modules/ic-datepicker/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in node_modules/ic-datepicker/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in node_modules/ic-datepicker/node_modules/@angular/core/index.d.ts, resolving symbol IcDatepickerModule in node_modules/ic-datepicker/dist/src/ic-datepicker.module.d.ts, resolving symbol IcDatepickerModule in node_modules/ic-datepicker/dist/src/ic-datepicker.module.d.ts`

**Note!**

I cut the contents from  **node_modules\ic-datepicker\dist** and the removed all contents from **node_modules\ic-datepicker** directory and pasted the contents from **node_modules\ic-datepicker\dist** to **node_modules\ic-datepicker\** direcotry.

then updated the import statements to:

`import { IcDatepickerModule } from 'ic-datepicker';`

And worked! So, the problems seems to be with the npm package, and requires a fix.

**Comment by IckleChris** [comment]
@naveedahmed1 Is this still an issue? I don't get any errors when I build the demo app, which is an Angular CLI project using the datepicker component. What version do you have installed?

**Comment by naveedahmed1** [comment]
Yes, I tested it with latest release and still an issue. 

I am using Angular 4 RC 5, Angular CLI 1.0.0-rc.2

**Comment by IckleChris** [comment]
I have an Angular CLI project (v1.0.0-beta.30) that I can successfully build with v0.0.9 of this component, so I'll have to dig around to find out what has changed.

**Comment by naveedahmed1** [comment]
Kindly check it with latest version V 1.0.0

**Comment by IckleChris** [comment]
I can replicate the error exactly with a freshly generated Angular 4, project with CLI v1. I don't however know what the cause of the error is.

**Comment by IckleChris** [comment]
After an awful lot of testing and tweaking I think this issue is finally resolved. Can you try with `v0.0.10` and report back?. I've tested it in my Angular v4 project and it builds successfully.

**Comment by naveedahmed1** [comment]
Finally, its working! Great job @IckleChris 👍
