### ISSUE TITLE
Tab / Shift + Tab Doesn't work

### ISSUE THREAD

**Issue by naveedahmed1** [IckleChris/ic-datepicker#8]
While filling forms user often use Tab / Shift + Tab keys to switch between the form fields. When the focus is on the Datepicker field pressing Tab/ Shift + Tab keys doesnt set the focus on the next/previous form field.

Can you please have a look?

**Comment by IckleChris** [comment]
Thanks, this has been resolved in `0.0.9`

**Comment by naveedahmed1** [comment]
Thanks man, this was quick!
