### ISSUE TITLE
DD.MM.YYYY support?

### ISSUE THREAD

**Issue by ali-kamalizade** [IckleChris/ic-datepicker#9]
First off, this datepicker looks very nice and I'd like to use it in one of my projects.
What I'd need is the DD.MM.YYYY (e.g. 01.04.2017) format?
Is there an option available so that I can use this date format?
Thanks in advance.

**Comment by IckleChris** [comment]
Thanks!

If you are talking about the value that is displayed in the input field you can use the `displayFormat` option and pass in any format supported by [moment.js](http://momentjs.com/docs/#/parsing/string-format/). If you mean the model value you can use the `stringModelFormat` option with `modelType` set to `string`.

e.g. 
```
{
    displayFormat: 'DD.MM.YYYY'
}
```

Let me know if this isn't what you meant.

**Comment by ali-kamalizade** [comment]
Thanks for the quick reply!
Awesome. That looks to be exactly what I was looking for.
Will try this.
